site_name: 'オーケストレーションツール'

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  hljs_languages:
    - 'yaml'
    - 'dockerfile'
    - 'ruby'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

google_analytics: ['UA-137771737-1', 'y-ohgi.com']

extra_css:
  - 'assets/custom.css'

extra_javascript:
  - 'assets/custom.js'

nav:
  - 'Home': 'index.md'
  # - 'WIP: docker-compose':
  #   - 'About': 'docker-compose/index.md'
  #   - 'ハンズオン': 'docker-compose/handson.md'
  - 'swarm':
    - 'About': 'swarm/index.md'
    - 'ハンズオン': 'swarm/handson.md'
  - 'WIP: ECS':
    - 'About': 'ecs/index.md'
    - 'AWSの準備': 'ecs/aws.md'
    - 'nginxを動かす': 'ecs/nginx.md'
    - '自作アプリを動かす': 'ecs/selfmade.md'
  - 'Kubernetes':
    - 'Kubernetesとは': 'kubernetes/index.md'
    - 'GKEを触ってみる': 'kubernetes/cluster.md'
    - 'Objectsについて知る': 'kubernetes/objects.md'
    - 'コードで定義する': 'kubernetes/manifest.md'
    - '自作アプリを動かす': 'kubernetes/selfmade.md'
    - '最後に': 'kubernetes/finally.md'
